FROM python:3.7.3

ENV PROJECT_DIR="/Applications/laravel/docker-laravel/scraping/"

ADD app/ $PROJECT_DIR

WORKDIR $PROJECT_DIR

RUN apt-get update
RUN apt-get -y install \
    tesseract-ocr \
    tesseract-ocr-jpn
RUN apt-get clean

# 3. 必要なpythonライブラリをpipでインストール
RUN pip install --upgrade pip; \
    pip install \
    pillow \
    pyocr \
    pytesseract

RUN pip install -r requirements.txt

CMD ["python", "app.py"]
